services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: xcybersecurity_app
        volumes:
            - .:/var/www/html
            - ./storage:/var/www/html/storage
            - ./public:/var/www/html/public
        ports:
            - "8000:80"
        depends_on:
            - db
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=xcybersecurity
            - DB_USERNAME=root
            - DB_PASSWORD=

    db:
        image: mysql:8.0
        container_name: xcybersecurity_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: # Leave blank if no password
            MYSQL_DATABASE: xcybersecurity
            MYSQL_USER: root
            MYSQL_PASSWORD: # Leave blank if no password
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
